name: Release metrics

on:
  release:
    types: [ published ]

jobs:
  build-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Configure credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.CI_AWS_ROLE_ARN }}
          aws-region: us-west-2

      - name: Build and upload metrics
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          UPLOAD: 'true'
          RELEASE_METRICS: 'true'
          IDENTIFIER: 'null' # Only needed for pull requests
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: aws-sdk-kotlin-service-build
          source-version-override: ${{ github.ref }}
          env-vars-for-codebuild: GITHUB_REPOSITORY, UPLOAD, RELEASE_METRICS, IDENTIFIER

permissions:
  id-token: write
  contents: read
